#filename:.travis.yml
dist: trusty
sudo: false
cache:
  bundler: true
  directories:
  - cache/
notifications:
  email: false
language: c
compiler: gcc
env:
  global:
  - PACKAGE=vlmcsd
  - USER=arition
  - REPO=openwrt-vlmcsd
  matrix:
  - OSVER=OpenWrt   SDK_URL=https://downloads.openwrt.org/snapshots/trunk/ipq806x/generic/OpenWrt-SDK-ipq806x_gcc-5.3.0_musl-1.1.16_eabi.Linux-x86_64.tar.bz2
  - OSVER=LEDE      SDK_URL=https://downloads.lede-project.org/releases/17.01.0/targets/ipq806x/generic/lede-sdk-17.01.0-ipq806x_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64.tar.xz
  - OSVER=OpenWrt   SDK_URL=https://downloads.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
  - OSVER=LEDE      SDK_URL=https://downloads.lede-project.org/releases/17.01.0/targets/ar71xx/nand/lede-sdk-17.01.0-ar71xx-nand_gcc-5.4.0_musl-1.1.16.Linux-x86_64.tar.xz
  - OSVER=OpenWrt   SDK_URL=https://downloads.openwrt.org/chaos_calmer/15.05.1/ramips/mt7620/OpenWrt-SDK-15.05.1-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
  - OSVER=LEDE      SDK_URL=https://downloads.lede-project.org/releases/17.01.0/targets/ramips/mt7620/lede-sdk-17.01.0-ramips-mt7620_gcc-5.4.0_musl-1.1.16.Linux-x86_64.tar.xz
  - OSVER=OpenWrt   SDK_URL=https://downloads.openwrt.org/chaos_calmer/15.05.1/brcm63xx/generic/OpenWrt-SDK-15.05.1-brcm63xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
  - OSVER=LEDE      SDK_URL=https://downloads.lede-project.org/releases/17.01.0/targets/brcm63xx/generic/lede-sdk-17.01.0-brcm63xx-generic_gcc-5.4.0_musl-1.1.16.Linux-x86_64.tar.xz
  - OSVER=OpenWrt   SDK_URL=https://downloads.openwrt.org/chaos_calmer/15.05.1/bcm53xx/generic/OpenWrt-SDK-15.05.1-bcm53xx_gcc-4.8-linaro_uClibc-0.9.33.2_eabi.Linux-x86_64.tar.bz2
  - OSVER=LEDE      SDK_URL=https://downloads.lede-project.org/releases/17.01.0/targets/bcm53xx/generic/lede-sdk-17.01.0-bcm53xx_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64.tar.xz
  - OSVER=OpenWrt   SDK_URL=https://downloads.openwrt.org/chaos_calmer/15.05.1/brcm47xx/generic/OpenWrt-SDK-15.05.1-brcm47xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
  - OSVER=LEDE      SDK_URL=https://downloads.lede-project.org/releases/17.01.0/targets/brcm47xx/generic/lede-sdk-17.01.0-brcm47xx-generic_gcc-5.4.0_musl-1.1.16.Linux-x86_64.tar.xz
  - OSVER=OpenWrt   SDK_URL=https://downloads.openwrt.org/chaos_calmer/15.05.1/mvebu/generic/OpenWrt-SDK-15.05.1-mvebu_gcc-4.8-linaro_uClibc-0.9.33.2_eabi.Linux-x86_64.tar.bz2
  - OSVER=LEDE      SDK_URL=https://downloads.lede-project.org/releases/17.01.0/targets/mvebu/generic/lede-sdk-17.01.0-mvebu_gcc-5.4.0_musl-1.1.16_eabi.Linux-x86_64.tar.xz
  - OSVER=OpenWrt   SDK_URL=https://downloads.openwrt.org/chaos_calmer/15.05.1/x86/generic/OpenWrt-SDK-15.05.1-x86-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
  - OSVER=LEDE      SDK_URL=https://downloads.lede-project.org/releases/17.01.0/targets/x86/generic/lede-sdk-17.01.0-x86-generic_gcc-5.4.0_musl-1.1.16.Linux-x86_64.tar.xz
  - OSVER=OpenWrt   SDK_URL=https://downloads.openwrt.org/chaos_calmer/15.05.1/x86/64/OpenWrt-SDK-15.05.1-x86-64_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
  - OSVER=LEDE      SDK_URL=https://downloads.lede-project.org/releases/17.01.0/targets/x86/64/lede-sdk-17.01.0-x86-64_gcc-5.4.0_musl-1.1.16.Linux-x86_64.tar.xz
install:
- mkdir -p $TRAVIS_BUILD_DIR/local ; cd $TRAVIS_BUILD_DIR/local
- wget "http://us.archive.ubuntu.com/ubuntu/pool/main/c/ccache/ccache_3.3.3-1_amd64.deb"
- dpkg -x *.deb .
- mkdir -p $TRAVIS_BUILD_DIR/cache ; cd $TRAVIS_BUILD_DIR/cache
- wget -c $SDK_URL
- mkdir -p $TRAVIS_BUILD_DIR/sdk ; cd $TRAVIS_BUILD_DIR/sdk
- export FILE=$TRAVIS_BUILD_DIR/cache/$(basename $SDK_URL)
- file $FILE
- if [ "$OSVER" = "OpenWrt" ]; then tar xjf $FILE && SDK_DIR="OpenWrt-SDK-*"; elif [ "$OSVER" = "LEDE" ]; then tar Jxf $FILE && SDK_DIR="lede-sdk-*"; fi
- cd $TRAVIS_BUILD_DIR/sdk/$SDK_DIR
- mkdir package/$PACKAGE
- ln -s $TRAVIS_BUILD_DIR/Makefile package/$PACKAGE/
- ln -s $TRAVIS_BUILD_DIR/files package/$PACKAGE/
script:
- export PATH=$TRAVIS_BUILD_DIR/local/usr/bin:$PATH
- cd $TRAVIS_BUILD_DIR/sdk/$SDK_DIR
- export SDK_DIR=$(basename `pwd`)
- export PATH=$TRAVIS_BUILD_DIR/sdk/$SDK_DIR/staging_dir/host/bin:$PATH
- pushd staging_dir/toolchain-*
- TOOLCHAIN_DIR=$(basename `pwd`)
- export PATH=$TRAVIS_BUILD_DIR/sdk/$SDK_DIR/staging_dir/$TOOLCHAIN_DIR/bin:$PATH
- popd
- ./scripts/feeds update packages >/dev/null
- make defconfig
- make package/vlmcsd/compile V=s
- find $TRAVIS_BUILD_DIR/sdk/$SDK_DIR/bin/
- find . -name *vlmcsd*.ipk -exec cp {} $TRAVIS_BUILD_DIR \;
- cd $TRAVIS_BUILD_DIR/
- chmod a+x $TRAVIS_BUILD_DIR/deploy.sh
after_success: "$TRAVIS_BUILD_DIR/deploy.sh"
before_deploy: git fetch --tags
deploy:
  provider: releases
  api_key:
    secure: "A3e2+K9AXpAr2obsn8Zda94qvFWumk3k3YBnPPV2Q+BS5r2MEWaa9MylGj8cuPJQvWI5Q9FEL86pVxRPfOBKcD0wUjH4ZD/zODWpjWv/3fD2cJLdGup227hc8mvjnp72wZOJ/v5NngB7NLJQJd25oHESKdcFw//XulrJJzwC/m0uM21epIqsyOWrspZUxsM05oDWyNoksYN57oroWp/uiK9kokkJibrtqhtpFOvYKqrSIaW1rsA+MjQDsOQLL2jF3bBWkp1zbj8sgavgpujBUambFWDdIFE0dH7BO07R8ZxbdZp26eE/2YwVzB+h/xnWOx1db/vMImVFzIAL6xAKfORJcPTIdML2MUIBfvmxpW6b1T5aAdQQijFxB90oWpFL3VSflOFG2UQm6LW93C4gQybosJWh6W0M/i/cOAZB1Ejs0hDXNrQtLo+U2I8QrybTlFOLV1EHk9ymNlGumwoN22Jupv7wDMbQ/1nA7Eqp3N86VV9C5Ef3quMSw9n+jSe4RrcWZGdySMkSv7VdKt2OB5490unSYh7wz6Ic72UcfNawmo3oJvgv5riMNekl+PbbfpGs/V0+QqThJvqLtsU2DO5mtCHvWl7JO4pD6eYQd1Sjtj37SDCy+P2gnFJrBXR24U9JKIyYCrYBBOzod2wc3Z6sWMMc4wtTySfBvDpov6g="
  skip_cleanup: true
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/*.ipk"
  on:
    tags: true
    all_branches: true
